services:
    app:
        image: us-docker.pkg.dev/voltaic-country-280607/gcr.io/vuanem-moengage:${GH_REF:-master}
        build: .
        container_name: vuanem-moengage
        volumes:
            - ./${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/{GOOGLE_APPLICATION_CREDENTIALS}
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/{GOOGLE_APPLICATION_CREDENTIALS}
        cpu_count: 4
