import { Joi, timestamp, number } from '../../joi';
import { qb } from '../../bigquery.service';
import { createUserStream } from '../pipeline.utils';

export const getUserAttributesStream = createUserStream({
    qb: qb
        .withSchema('OP_CDP')
        .from('Moengage__UserAttribute')
        .select([
            'countdown_birthday',
            'dob',
            'expire_date_group',
            'first_campaign_name',
            'first_medium',
            'frequency',
            'is_customer',
            'last_engagement_date',
            'last_engagement_place',
            'last_location_code',
            'last_purchase_channel',
            'last_rating_date',
            'last_rating_point',
            'last_trandate',
            'loyalty_group',
            'loyalty_point',
            'moe_cr_from',
            'moe_ip_city',
            'redeem_amount',
            't_rev',
            'u_em',
            'u_id',
            'u_mb',
            'u_n',
            'user_name',
        ]),
    schema: Joi.object({
        countdown_birthday: number,
        dob: timestamp,
        expire_date_group: timestamp,
        first_campaign_name: Joi.string(),
        first_medium: Joi.string(),
        frequency: number,
        is_customer: Joi.boolean(),
        last_engagement_date: timestamp,
        last_engagement_place: Joi.string(),
        last_location_code: Joi.string(),
        last_purchase_channel: Joi.string(),
        last_rating_date: timestamp,
        last_rating_point: number,
        last_trandate: timestamp,
        loyalty_group: Joi.string(),
        loyalty_point: number,
        moe_cr_from: Joi.string(),
        moe_ip_city: Joi.string(),
        redeem_amount: number,
        t_rev: number,
        u_em: Joi.string(),
        u_id: Joi.string(),
        u_mb: Joi.string(),
        u_n: Joi.string(),
        user_name: Joi.string(),
    }),
    customerId: (row) => row.u_mb,
});
